version: '3.7'

services:
  app:
    container_name: ddd-sample-app
    build:
      context: ./
    volumes:
      - ./:/app
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      - db
      - test_db
    links:
      - db
      - test_db
    tty: true

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    tty: true

  test_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    tty: true